---
layout: "../../layouts/BlogLayout.astro"
title: 'The dream job'
publishedDate: 2023-02-17
description: 'Some thoughts I had about what having a "dream" job means, whether it makes sense to pursue it'
author: 'Daniel Velasquez'
tags: ["career"]
---

* The dream job
A friend of mine recently put me on to [[https://www.relay.fm/cortex ][a podcast called Cortex]]. The hosts of this show are two entrepreneurs that discuss, among other things, entrepreneurship. Some of their discussions have made me re-think the idea of a "dream job", as well as what my "dream job" would be.

In one of the episodes, [[https://pca.st/KqpS#t=2277.0][one of the hosts mentions that]] many people talk about how important it is to find a job that you really love. He seems to imply that this advice a bit misguided. 

The host said that there are "precious, precious few people" who wake up in the morning and feel like they really love their job. The host works as a content creator and business owner. He doesn't quite say that he loves his work, but rather that he can't think of any other work that would be better suited for his personality.

I agree with the host in that there are probably very, very few people who truly love their jobs. I think a large part for this is that many, if not most, people in the world are unfortunately living in life circumstances where they don't have the luxury to choose their job, much less optimize it for their personal preference. Many people are forced to work whatever job they were lucky enough to get by waking up early every morning and putting their head down throughout the day, so that they could feed and shelter themselves and their families. I recognize this, but I won't expand on this. In this post, I'll limit my discussion to the small subset of people in the world who have the ability to change their job to better suit their preferences.

It seems like there are two different perspectives on what the most important quality of a job is:
- You feel excited to do it every day because you love it so much.
- It allows you to enjoy your life outside of work as much as possible.

Of course, both are important. But I believe that if you were to ask people which one is /more/ important, you would get different answers.

I believe this podcast host would probably pick the second choice as the most important quality. In the first episode of the podcast, he talks about how he really doesn't like work. He [[https://pca.st/episode/9a6377e0-ec2e-0132-1127-059c869cc4eb][talks about]] how he spends a lot of time carefully calculating how he could do the least amount of work and get the most output for it. In this sense, I assume "output" can either refer to financial returns or completion of tasks.

I, in contrast, would pick the first choice. I don't know why. But, I think it's because I may have been drinking some Kool-Aid throughout my life without even realizing it. I feel like through movies, books, and personal accounts, I've somehow began to admire this idea of a person who is really good at their career and do big positive things as a result.

Another reason I would pick the first one might be that, thanks to [[https://www.goodreads.com/en/book/show/66354][this really good book]], I'm a big believer in the idea that, [[https://en.wikipedia.org/wiki/Flow_(psychology)#Effects][a lot of happiness]] can come from being [[https://en.wikipedia.org/wiki/Flow_(psychology)#Characteristics][in a state of challenge in a domain and difficulty that matches your skill set]]. So, I believe that many people could get a lot of happiness from choosing a job that they like and would be good at. This could give them a sense of purpose.

I feel like sometimes people mistakenly believe that they would be happy if they didn't have to do any work at all. But in reality, I feel like jobs give a lot of people some sense of being needed, which I think is important. Without their jobs, I feel like many people would lose this feeling of being needed which would in turn start to feel like a lack of purpose. This lack of purpose might lead to apathy and a lower overall sense of happiness. 

But of course, everyone is different. I believe many people would be much happier without a job. And many people would be much happier with a job. I'm just saying that if I had to guess, I /think/ that more people would be happier with a job, as long as that job suits their interests and skills.

** On to me
I've always been someone with a lot of side projects. The goal of my side projects has always been to build something that I love using the skills that I am good at. The difficult thing about side projects is the /"side"/ part. When I was studying at the university, and in a lot of my jobs, I felt like I had to split my time into two. One part of my time would go into the things that I /had/ to do. The other part of my time would go into the things that I /wanted/ to do. As someone that would pick the first choice, it only felt natural for me to try to see how I could somehow merge the two; find a job that pays me to do the things that I love to do. That way, instead of needing to prioritize one and neglect the other (or prioritize both over other things important in my life), I could do both at once! 

As such, I've spent a lot of time trying to figure out how I could somehow determine what job would suit my interests and skills.

At first, I thought that entrepreneurship was obviously the answer. But after some reflection, (*TODO cite*), I realized that it makes more sense to start by creating a list of qualities that I would desire in a job. The idea is that I could use this list as a guide to navigate my career.

It would be an oversimplification to treat this list as a checklist, and qualify a given job by the amount of items that it shares with my quality list. The answer of whether a given job shares a quality with my list is not binary. It is a sliding scale. If two of my list qualities are "being easy to commute to" and "being interesting," a job might meet score a 40% at first criterion and an 85% at the other.

Below are the top three qualities I seek in a job, in no particular order. If I'm being honest, having a job that gives a really high income or comes with bragging rights would be nice too. But vanity aside, I think these are better reasons:

** The ability to learn and grow in things that are practically and technically interesting to me
I've always been a very curious person and I've been very interested in learning technical things in the realm of computer science. I've also been interested in practical things that are useful in my career.

I feel strongly about these interests because learning these things is just fun to me and I feel like I can get good at them, which is also fun.

This isn't on my list just because of fun though. I'm also motivated by fear. I've seen how many people older than me, who at one point were developers like me, at a certain age left behind their days of learning technical details to transition into leadership and design roles. This makes me worry that my time to learn technical things has a deadline. I worry that too soon, I will become too old and too disinterested in learning technical things.

Also, it seems like at around the age of 30-40, [[https://www.scientificamerican.com/podcast/episode/cognitive-decline-sets-in-around-ag-12-01-08/][the brain starts to gradually become worse]] at learning new things. So, I'd like to learn as much and as fast as possible while I still can.

** Working with talented people
This point might be largely related to the first point, because more often than not, to get learn and grow in a domain, you will need to work with people that are talented and can help you grow.

But, I'll mention it here for emphasis. I like to constantly put myself in rooms where I have tons of things to learn from others. It feels like this would be a very effective way to constantly find ways in which I'm doing things wrong and improve on them.

Right now, I am extremely lucky to work with someone that constantly makes me feel like a novice. My experience and accomplishments might seem nice in isolation, but they pale in comparison to theirs. Because they've constantly shown me ways in which I can improve, I've been able to learn and accomplish things really quickly.

** Working on a product that I am passionate about
I believe that in an ideal job, I'd be building a product or service that I genuinely care about. Maybe I'll care because I love the domain, or because it solves a problem I personally find important and relate to, or because its for a group of people that I genuinely care about.

To be honest, I'm not quite sure what this would passion would be yet, because so far I've optimized my personal projects and professional experience to revolve around technical learnings over interest in a domain. I guess it would be cool to be passionate not only about how I learn to build things but also about what gets built as a result.

I do know that I've gotten a lot of enjoyment from my limited experiences tutoring and teaching others how to do things. So right now I believe that if I were to work on a product that helps others learn, I might become passionate about the product. But, I'm not totally sure right now.

Right now, I get a lot of satisfaction from the building part alone.
