#+BEGIN_SRC yaml
---
layout: "../../layouts/BlogLayout.astro"
title: 'The challenge of writing'
publishedDate: 2024-03-18
description: 'The reason that writing accessible content can be difficult and one approach to make it easier'
author: 'Daniel Velasquez'
tags: ["writing"]
---
#+END_SRC

The extent to which I reap [the benefits of writing](*TODO: CITE*) depends on the level of effort that I put in. If I try to write things with a lot of explanation, detail, and research, I will explore more, challenge more, remember more, and have more to reflect on in the future. This is why whenever I write about my learnings, I try to explain them very well, as if the content were to be read by an absolute beginner. This approach also comes with the obvious benefit that if someone were to come across my writings, there's a higher chance that they will understand the content and get something out of it.

However, this isn't always easy. This post is about the challenge of writing accessible content, and one approach I take to try to address that challenge.
  
** Curse of knowledge makes it hard for me to make content accessible
It is sometimes hard for me to make content accessible because of [[https://en.wikipedia.org/wiki/Curse_of_knowledge][the curse of knowledge]]. The curse of knowledge is a cognitive bias that makes it difficult for a person with experience to explain things to beginner. A person with experience might have a difficult time explaining because in their explanations, they might use sentences that seem trivial and easily understandable to them, but totally perplex the beginner. This is because after high levels of mastery, a person with experience might subconsciously wrongly assume that others know the things that they consider to be basic; it becomes difficult for them to put themselves in the perspective of the beginner and remember their challenges.

I think that it becomes difficult for those with experience to put themselves in the perspective of a beginner because of the way that people learn. When people learn about a foreign subject, a lot of the things that at one point seemed unintuitive, confusing, and strange to them, will start to seem intuitive, straight-forward, and natural to them. One of my favorite quotes summarizes this phenomenon: "All of physics is either impossible or trivial. It is impossible until you understand it, and then it becomes trivial" - Ernest Rutherford. Those who have spent a long time feeling like foundational content is trivial, may lose their ability to relate to beginners.

I feel like this happens to me to some extent when I'm writing or explaining something. I can forget the perspective of an absolute beginner, so I might explain something assuming that they already know things that they don't. Sometimes I even do the reverse. I sometimes mistake the things that are confusing the listener and start elaborating on things that are trivial to everyone in the room.

** Solution

In an effort to write content in an accessible way, I am trying to write down the things that I learn, almost as soon as I learn them. By doing so, I might bypass the curse of knowledge. At the instant of learning something new, I'm at the state of transition between something being impossible and trivial. In this state, I can remember why I felt like the thing that I've just learned is impossible, and simultaneously feel like it is trivial. So, if I were to write down the learning at that instant, I might be able to write down an explanation that would be understandable to someone who thinks that it is impossible, while detailing the knowledge of someone who thinks it is trivial.
