---
layout: "../../layouts/BlogLayout.astro"
title: 'Bad reasons for being an entrepreneur'
publishedDate: 2023-02-17
description: 'Some bad reasons as to why one should be an entrepreneur'
author: 'Daniel Velasquez'
tags: ["career"]
---

* Bad reasons for being an entrepreneur
For a long time, almost every day after work, I would spend hours trying to build my own income-generating business. I sacrificed time with my girlfriend, personal interests, time talking to family, etc. in doing so. I did this because I thought that the only job that would suit me is being an entrepreneur. I had several reasons:
- Starting and running a business is almost universally regarded as a difficult thing to do. So, if I could do this, other people become impressed and might even feel some sense of admiration towards me.
- Entrepreneurs get better financial returns relative to the amount of work that they put in. 
- It would be easier for me to get paid for doing what I love as an entrepreneur rather than as an employee.
- Entrepreneurs (in some cases) have more some freedom with when and how they want to work.
- Accomplishing big goals is more exciting and more motivating when one is an entrepreneur than when one is an employee.

I had two earnest attempts. In my second attempt, I worked with two friends. We worked together for roughly six months before deciding to disband. Afterward, I met up for drinks with one of the friends to catch up and reflect on our time working together. As we reflected, my friend pressed me about why I decided in the first place that I wanted to do entrepreneurship. I gave him the reasons above. But, he made me realize that, for me specifically, two of these reasons are false, one of these reasons is a bad reason, and only two of them are valid. The two that are valid, of course, come with difficult trade-offs. So, they would only be good reasons if I would be willing to make sacrifices. I'll analyze each reason to show why.

** Bad reasons
*** Entrepreneurs get respect and admiration from others
This is probably true. But I don't think this is a good reason. I mean, it's just vanity. It's so vain that I barely wanted to put this reason here out of embarrassment. But, hey, I wanted to be honest.

I could be wrong, but I believe that when someone who wants admiration, gets admiration, they will get a higher happiness level because of this for a short while. But afterward, everything else held equal, their happiness level will normalize to what it was before. In other words, I feel like admiration and excess income behave similar in this way. They both seem to me to be events in the so-called [[https://en.wikipedia.org/wiki/Hedonic_treadmill][hedonic treadmill]].

So, in short, this is a bad reason that also does not justify being an entrepreneur.

** False reasons
*** Entrepreneurs get better financial returns relative to the amount of work that they put in
I think this reason is straight-up false most of the time. It might be true for a small portion of entrepreneurs that are wildly successful. But even then, this is most likely true for those who are very lucky, or for those who have spent many difficult years working much harder and stressing out much more than their employee counterparts.

A podcast host of [[https://www.relay.fm/cortex][a show I listen to]], hosted by two entrepreneurs, [[https://pca.st/KqpS#t=5112.0][once spoke about how]] to become a successful entrepreneur, he had to work so hard that for years, he sacrificed the entirety of his social life and his sleep, to be able to start his business. I could be wrong, but I believe that to this day he and his co-host work probably around the same as the average employee. But, this is after many years of a lot more work.

So, I believe this is often a false reason that does not justify being an entrepreneur.

*** It would be easier for me to get paid for doing what I love as an entrepreneur rather than as an employee
This one can vary a lot on the person. For me in particular, I don't think this would be true.

The things that I know I like, in the realm of work, in no particular order, are:
- programming languages
- low-level concepts about computers and system development
- teaching people things
  
At least to me right now, it seems like these interests are a bit difficult to commercialize. Programming languages are notorious for [[https://www.stroustrup.com/bs_faq.html#C++success][having an exceedingly low success rate]]. I could be wrong, but I believe that even if I where a programming language that became popular and widely used, it would be very difficult to make money from it.

There's probably a better chance of someone being able to build and commercialize a product with a knowledge in system development. But a successful product would most likely come from an expert that made some bleeding-edge discovery in the field...aka not me. I'm at the very beginning of my learnings in systems development. So at least right now, I would more likely be able to get paid as an entry-level systems developer at a company than be pushing [[https://paulgraham.com/getideas.html][the frontier of knowledge]].

The remaining interested that I listed is of a slightly different category. This is more of a "domain," rather than a technical, interest. If I wanted to make my career about teaching people things, I could either join a company with a product that specializes in teaching others. Or, I could create a product or service to do so. It seems to me like doing the first would probably be much, much easier.

** Valid reasons
*** Entrepreneurs (in some cases) have some more freedom with when and how they want to work
I believed that entrepreneurs have more freedom with their working conditions because I grew up with my father, who has always been an entrepreneur. While my friends' parents would be waking up at 6am to commute (sometimes for hours) to get to their jobs across town at 8am, my father would probably wake up around 9 or 10am and have time to hangout in the morning before jumping onto calls in the comfort of his own home. He also didn't have a boss. He had nobody above him to be would track his working hours, his accomplishments, or would critique him.

This is obviously all really nice but there's a flip side. My friends' parents would come home at 6pm with the freedom to completely forget everything about work. My dad did not have this luxury. He was responsible for the operation of a business. If things didn't go well, it would be very bad news for him and all the people that depended on a salary from his company. So, he would often think about work and have to jump on calls, sometimes late afternoons, weekends, or in vacations.

It is true that as an entrepreneur, I'd have a certain level of greater freedom because I wouldn't be held accountable by a boss and I wouldn't be forced to work 9-5. But, I'd also be forced to hold myself accountable which can be very difficult. It also means I may end up working more than an average employee. And, I won't have a built-in schedule that defines when I can take time off and relax without needing to worry about work. Actually, I believe one of the podcast hosts that I mentioned earlier would agree. In an episode, [[https://pca.st/fGVr#t=2157.0][he spoke about how he needed to work 6 days a week, sometimes 7]]. And, how it's been very difficult for him to take a vacation [[https://pca.st/fGVr#t=3425.0][because it has always felt like he can do more work]].

*** Accomplishing big goals is more exciting and more motivating when one is an entrepreneur than when one is an employee
This point might be true. But, similar to the former point, it comes with a trade-off. 

Suppose there are two hypothetical people, who are both separately building their own product. One is an entrepreneur who is intends this product to be a revenue source for their own business; The other is an employee who was tasked to build this within their company. Assuming all else is held equal, (neither person knows if their product will be successful, both people have the same amount of people and talent on their team, both people have the same level of authority and responsibility, etc), I believe that the entrepreneur will work much harder, have much more stress, and incur many more risks than the employee counterpart. As a result, accomplishments for the entrepreneur will feel much more rewarding an exciting, than they would for the employee.

So, in sum, it seems like the highs for me would feel higher, but the stress, work, and risks are higher too.

** Reflection
The reason I wanted to be an entrepreneur is that I thought it would be the way to obtain my dream job. This conversation made me realize that I may have decided that I wanted to be an entrepreneur, and tried to retroactively fit that image to be my dream job. Instead, it might make more sense to list qualities that a job would have be and from there, see what jobs I would like. Afterward, I'll have a clearer picture if entrepreneurship really is a good fit for me. The answer might be no but that's okay. At some point in the future it might change to a yes.


I'll speak more about the idea of a "dream job" in my next post. 
