#+BEGIN_SRC yaml
---
layout: "../../layouts/BlogLayout.astro"
title: 'Why I Write'
publishedDate: 2024-03-18
description: 'The reasons that I have started writing'
author: 'Daniel Velasquez'
tags: ["career"]
---
#+END_SRC

Recently, I've been trying to get better at writing down my thoughts. It's funny to me that I'm doing this because I didn't think that I would ever care about writing. There are several reasons I have for not writing:
- I'm already busy in my life with several other commitments, desires, and responsibilities.
- Writing is a difficult and time-consuming process.
- I don't particularly love writing. I was never good at it in school or took any special classes for it.

I started writing because I realized that its benefits outweigh its costs:
- Writing helps me explore my ideas and thereby understand my opinions and desires better. Also, writing helps me have new thoughts at a greater level of nuance.
- Writing helps me remember my learnings better.
- I like documenting.
- When I'm older, I'll be able to see what my younger self was thinking and feeling by looking back at my writings. It could be really fun to analyze the changes in my thoughts and personality as a function of time.
- When I'm older, I'll be able to re-teach myself about some of the things that I've forgotten about by looking back at my writings.

- It's good to practice the skill of expressing myself clearly and concisely.

In this post, I'll expand on these reasons that I have to write.

** Explore my thoughts and understand my opinions and desires better

I often feel like I want to explore and document the ideas that I have. I like to explore ideas a little bit by thinking about them when I'm doing monotonous tasks or when I have some free time. Exploring these ideas via thinking is nice but can only get me so far. Often, I'll get to a point where I'll get distracted by something else or confused or bored. So, the exploration will end there.

Writing feels like a tool that I can use to help organize and structure my thoughts. This added structure helps me understand my ideas better. In structuring my thoughts, I'll often realize that my ideas have logical holes. If I put in effort to making the content that I write accessible, I'll often realize that I thought I knew something, but in reality I did not.

To fix the logical holes and learn the things that I thought that I knew, I often need to do additional research. With this research, I'll often realize that I'm wrong about something, which I appreciate. Other times, I'm able to add nuance to my ideas. Sometimes, I'll even get new ideas as a result.

** Writing helps me remember my learnings better

I have a lot of ideas and a bad memory. If I don't write consistently, I'll occasionally experience a big realization and feel really good about it, only for others to tell me that I've already had that realization, which makes me feel like I'm in an cycle of realizing something, forgetting it, and realizing it again. I'd like to avoid this cycle by making sure I forget my realizations as seldom as possible.

Writings helps me forget my realizations less often in two ways: 
- Some part of the process of writing something down helps me remember what I wrote down better.
- If I organize my writings, I believe that be able to get refer back to my writings and search through them easily.

** I like documenting
It might sound like I'm contradicting myself. One of the reasons that I wrote for not writing is that I don't love writing. This is true. I don't love writing. But for some reason I do like documenting. I consider these to be different. Up until recently, the majority of writing I did was for school.  In school, almost all of my writing assignments were long, complicated essays on topics I did not know as well as my teachers or professors wanted me to. In school, I was awfully susceptible to extreme procrastination. It is very painful to write ten pages about a topic that you have no idea about. It is even more painful to write ten pages about a topic that you have no idea about when you haven't started and it's 2AM and it's due in six hours. As a result, for a long time, I associated writing with massive aversion and stress.

Those years are behind me now. Now I don't associate writing with these things. But, I still don't /love/ it. I kind of like it. I have more fun programming or learning about something I'm interested in.

I like writing to the extent that it lets me feel like I'm build something and explaining something. For me, this is documentation. By documenting things, whether it's for a project, or for work, or for things in my life, I get the feeling that I get to build a body of knowledge that is accessible and helps other people. And, I like this.

** Looking back when I'm older
One of the really cool things about 
** scraps

I strive to write down important ideas almost as soon as possible after having them. I feel like if I wait to write down the idea, I may forget it, lose interest in it, or forget the important details about it.

- I have a lot of thoughts and a bad memory. If I don't write consistently, I'll occasionally experience a big realization and feel really good about it, only for others to tell me that I've already had that realization, which makes me feel like I'm in an infinite realization cycle.

I created this website to share some of my writings, those that may be of interest to others.
