#+BEGIN_SRC yaml
---
layout: "../../layouts/BlogLayout.astro"
title: 'Why I Write'
publishedDate: 2024-03-18
description: 'The reasons that I have started writing'
author: 'Daniel Velasquez'
tags: ["career"]
---
#+END_SRC

Recently, I've been trying to get better at writing down my thoughts. It's funny to me that I'm doing this because I didn't think that I would ever care about writing. There are several reasons I could have for not writing:
- I'm already busy in my life with several other commitments, desires, and responsibilities.
- Writing is a difficult and time-consuming process.
- I don't particularly love writing. I was never good at it in school or took any special classes for it.

I started writing because I realized that its benefits outweigh its costs:
- Writing helps me explore my thoughts and thereby understand my opinions and desires better. Also, writing helps me have new thoughts at a greater level of nuance. 
- Writing enables me to challenge my ideas, by checking facts, evidence, and others' opinions.
- Writing helps me remember my learnings better.
- It's good to practice the skill of expressing myself clearly and concisely.
- When I'm older, I'll be able to see what my younger self was thinking and feeling by looking back at my writings. It could be really fun to analyze the changes in my thoughts and personality as a function of time.
- When I'm older, I'll be able to re-teach myself about some of the things that I've forgotten about by looking back at my writings.

In this post, I'll expand on these reasons that I have to write.

** Explore my thoughts and understand my opinions and desires better
