#+BEGIN_SRC yaml
---
layout: "../../layouts/BlogLayout.astro"
title: 'Why you should document your learnings'
publishedDate: 2024-03-18
description: 'One good reason to document your learnings'
author: 'Daniel Velasquez'
tags: ["career"]
---
#+END_SRC

Recently, I've been trying to get better at writing down my thoughts. I've realized that writing has several benefits:
- Writing helps me explore my thoughts and thereby understand my opinions and desires better. Also, writing helps me have new thoughts at a greater level of nuance. 
- Writing enables me to challenge my ideas, by checking facts, evidence, and others' opinions.
- Writing helps me remember my learnings better.
- I like documenting.
- It's good to practice the skill of expressing myself clearly and concisely.
- When I'm older, I'll be able to see what my younger self was thinking and feeling by looking back at my writings. It could be really fun to analyze the changes in my thoughts and personality as a function of time.
- When I'm older, I'll be able to re-teach myself about some of the things that I've forgotten about by looking back at my writings.
  
The extent to which I reap these benefits depends on the level of effort that I put in. If I simply write jot down some thoughts with little explanation and no research, I likely won't be exploring or challenging my ideas much.

---
I like writing about the things that I learn. I try to document my learnings in a way that is accessible because it'll helps me learn more.
- The more accessible I make content, the more effort I have to put into explaining the content, which means I'll learn more in the process.
- If I make my writings accessible, there's a higher chance that me in the future or another person will understand the content and get something out of it.

[[https://en.wikipedia.org/wiki/Curse_of_knowledge][The curse of knowledge]] makes it difficult to make content accessible. The curse of knowledge is that it's difficult for experts to explain things to a beginner. This happens when experts subconsciously wrongly assume that others know the things that they consider to be basic. As a result, seemingly trivial sentences for them perplex the student. This is because after high levels of mastery, it becomes difficult for experts to put themselves in the perspective of the beginner and remember their challenges.

I think the curse of knowledge is a product of the way that people learn. When people learn about a foreign subject, a lot of the things that at one point seemed unintuitive, confusing, and strange to them, will start to seem intuitive, straight-forward, and natural to them. One of my favorite quotes summarizes this phenomenon: "All of physics is either impossible or trivial. It is impossible until you understand it, and then it becomes trivial" - Ernest Rutherford. Experts are likely people who have spent a long time feeling like foundational content is trivial. So, this enables them to forget their ability to relate to beginners.

This is why whenever I realize that I am learning something important, I try to write it down immediately. By doing so, I might bypass the Curse of knowledge. At the instant of learning something new, I'm at the state of transition between something being impossible and trivial. In this state, I can remember why I felt like the thing that I've just learned is impossible, and simultaneously feel like it is trivial. So, if I were to write down the learning at that instant, I might be able to write down an explanation that would be understandable to someone who thinks that it is impossible, while detailing the knowledge of someone who thinks it is trivial.


** scraps

I strive to write down important ideas almost as soon as possible after having them. I feel like if I wait to write down the idea, I may forget it, lose interest in it, or forget the important details about it.

- I have a lot of thoughts and a bad memory. If I don't write consistently, I'll occasionally experience a big realization and feel really good about it, only for others to tell me that I've already had that realization, which makes me feel like I'm in an infinite realization cycle.

I created this website to share some of my writings, those that may be of interest to others.
